In [ ]:
# PCA Implementation from scratch (Following Experiment Steps)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Step 0: Create Sample Dataset
data = {
    'Feature1': [2,4,6,8,10],
    'Feature2': [1,3,5,7,9],
    'Feature3': [5,7,9,11,13]
}

df = pd.DataFrame(data)

print("Original Dataset:\n")
print(df)

Original Dataset:

   Feature1  Feature2  Feature3
0         2         1         5
1         4         3         7
2         6         5         9
3         8         7        11
4        10         9        13


In [ ]:
# Step 1: Standardize the dataset
X = df.values
mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std

print("\nStandardized Data:\n")
print(X_standardized)
print(pd.DataFrame(X_standardized))


Standardized Data:

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
          0         1         2
0 -1.414214 -1.414214 -1.414214
1 -0.707107 -0.707107 -0.707107
2  0.000000  0.000000  0.000000
3  0.707107  0.707107  0.707107
4  1.414214  1.414214  1.414214


In [ ]:
# Step 2: Compute Covariance Matrix
cov_matrix = np.cov(X_standardized.T)

print("\nCovariance Matrix:\n")
print(cov_matrix)


Covariance Matrix:

[[1.25 1.25 1.25]
 [1.25 1.25 1.25]
 [1.25 1.25 1.25]]


In [ ]:
# Step 3: Compute Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)


Eigenvalues:
 [ 3.75000000e+00  6.16297582e-33 -7.50963641e-17]

Eigenvectors:
 [[ 5.77350269e-01 -5.91397376e-17  4.12697760e-01]
 [ 5.77350269e-01 -7.07106781e-01 -8.16480357e-01]
 [ 5.77350269e-01  7.07106781e-01  4.03782597e-01]]


In [ ]:
# Step 4: Sort eigenvalues in descending order
sorted_index = np.argsort(eigenvalues)[::-1]

sorted_eigenvalues = eigenvalues[sorted_index]
sorted_eigenvectors = eigenvectors[:, sorted_index]

print("\nSorted Eigenvalues:\n", sorted_eigenvalues)


Sorted Eigenvalues:
 [ 3.75000000e+00  6.16297582e-33 -7.50963641e-17]


In [ ]:
# Step 5: Select top k eigenvectors
k = 2
principal_components = sorted_eigenvectors[:, 0:k]

print("\nTop Principal Components:\n")
print(principal_components)


Top Principal Components:

[[ 5.77350269e-01 -5.91397376e-17]
 [ 5.77350269e-01 -7.07106781e-01]
 [ 5.77350269e-01  7.07106781e-01]]


In [ ]:
# Transform data into new PCA space
X_pca = np.dot(X_standardized, principal_components)

print("\nTransformed Data (PCA Result):\n")
print(X_pca)


Transformed Data (PCA Result):

[[-2.44948974e+00 -9.07292297e-17]
 [-1.22474487e+00 -4.53646149e-17]
 [ 0.00000000e+00  0.00000000e+00]
 [ 1.22474487e+00  4.53646149e-17]
 [ 2.44948974e+00  9.07292297e-17]]


In [ ]:

pca_df = pd.DataFrame(X_pca, columns=['PC1', 'PC2'])

print("\nPCA DataFrame:\n")
print(pca_df)


PCA DataFrame:

        PC1           PC2
0 -2.449490 -9.072923e-17
1 -1.224745 -4.536461e-17
2  0.000000  0.000000e+00
3  1.224745  4.536461e-17
4  2.449490  9.072923e-17
