In [ ]:
import numpy as np
# Variance
data = np.array([1.2, 2.4, 3.5, 1.8, 4.0, 2.9])
# Calculating Mean
mean_val = np.mean(data)
# Calculating Variance
# Formula: sigma^2 = sum(x - mean)^2 / N
variance_val = np.var(data)
print(f"Dataset: {data}")
print(f"Mean: {mean_val:.2f}")
print(f"Variance: {variance_val:.2f}")

Dataset: [1.2 2.4 3.5 1.8 4.  2.9]
Mean: 2.63
Variance: 0.92


In [ ]:
# Two features (e.g., Study Hours vs Exam Scores)
study_hours = [2, 4, 6, 8, 10]
scores = [50, 60, 75, 85, 95]
# Calculate Covariance Matrix
cov_matrix = np.cov(study_hours, scores)
print("Covariance Matrix:")
print(cov_matrix)
print(f"\nCovariance between Hours and Scores: {cov_matrix[0, 1]:.2f}")

Covariance Matrix:
[[ 10.   57.5]
 [ 57.5 332.5]]

Covariance between Hours and Scores: 57.50


In [ ]:
A = np.array([[4, 2],
              [1, 3]])
# Calculate Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors (Columns):")
print(eigenvectors)

Matrix A:
[[4 2]
 [1 3]]

Eigenvalues:
[5. 2.]

Eigenvectors (Columns):
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [ ]:
# Standars Deviation
data_outliers = np.array([10, 12, 11, 13, 12, 100])

std_dev = np.std(data_outliers)
median_val = np.median(data_outliers)

print(f"Data with outlier: {data_outliers}")
print(f"Median (Robust to outliers): {median_val}")
print(f"Standard Deviation: {std_dev:.2f}")

Data with outlier: [ 10  12  11  13  12 100]
Median (Robust to outliers): 12.0
Standard Deviation: 32.96


In [ ]:
# Correlation between two variables
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10] # Perfectly linear

correlation_matrix = np.corrcoef(x, y)
r_value = correlation_matrix[0, 1]

print(f"Correlation Coefficient: {r_value}") # 1.0 means perfect positive correlation

Correlation Coefficient: 0.9999999999999999
